export const GET_WAREHOUSE_LIST = "GET_WAREHOUSE_LIST"; 
export const GET_WAREHOUSE_LIST_SUCCESS = "GET_WAREHOUSE_LIST_SUCCESS"; 
export const GET_WAREHOUSE_LIST_ERROR = "GET_WAREHOUSE_LIST_ERROR";

export const ADD_WAREHOUSE_LIST = "ADD_WAREHOUSE_LIST"; 
export const ADD_WAREHOUSE_LIST_SUCCESS = "ADD_WAREHOUSE_LIST_SUCCESS"; 
export const ADD_WAREHOUSE_LIST_ERROR = "ADD_WAREHOUSE_LIST_ERROR";

export const DELETE_WAREHOUSE_LIST = "DELETE_WAREHOUSE_LIST"; 
export const DELETE_WAREHOUSE_LIST_SUCCESS = "DELETE_WAREHOUSE_LIST_SUCCESS"; 
export const DELETE_WAREHOUSE_LIST_ERROR = "DELETE_WAREHOUSE_LIST_ERROR";

export const RESET_WAREHOUSE_LIST = "RESET_WAREHOUSE_LIST"; 
export const RESET_WAREHOUSE_LIST_SUCCESS = "RESET_WAREHOUSE_LIST_SUCCESS"; 
export const RESET_WAREHOUSE_LIST_ERROR = "RESET_WAREHOUSE_LIST_ERROR";