export const GET_WALLET_RULES_LIST = "GET_WALLET_RULES_LIST"; 
export const GET_WALLET_RULES_LIST_SUCCESS = "GET_WALLET_RULES_LIST_SUCCESS"; 
export const GET_WALLET_RULES_LIST_ERROR = "GET_WALLET_RULES_LIST_ERROR";

export const ADD_WALLET_RULES_LIST = "ADD_WALLET_RULES_LIST"; 
export const ADD_WALLET_RULES_LIST_SUCCESS = "ADD_WALLET_RULES_LIST_SUCCESS"; 
export const ADD_WALLET_RULES_LIST_ERROR = "ADD_WALLET_RULES_LIST_ERROR";

export const CHANGE_STATUS_WALLET_RULES_LIST = "CHANGE_STATUS_WALLET_RULES_LIST"; 
export const CHANGE_STATUS_WALLET_RULES_LIST_SUCCESS = "CHANGE_STATUS_WALLET_RULES_LIST_SUCCESS"; 
export const CHANGE_STATUS_WALLET_RULES_LIST_ERROR = "CHANGE_STATUS_WALLET_RULES_LIST_ERROR";

export const DELETE_WALLET_RULES_LIST = "DELETE_WALLET_RULES_LIST"; 
export const DELETE_WALLET_RULES_LIST_SUCCESS = "DELETE_WALLET_RULES_LIST_SUCCESS"; 
export const DELETE_WALLET_RULES_LIST_ERROR = "DELETE_WALLET_RULES_LIST_ERROR";

export const REST_WALLET_RULES_LIST = "REST_WALLET_RULES_LIST"; 
export const REST_WALLET_RULES_LIST_SUCCESS = "REST_WALLET_RULES_LIST_SUCCESS"; 
export const REST_WALLET_RULES_LIST_ERROR = "REST_WALLET_RULES_LIST_ERROR";