export const GET_LEAVE_MANAGEMENT_LIST = "GET_LEAVE_MANAGEMENT_LIST"; 
export const GET_LEAVE_MANAGEMENT_LIST_SUCCESS = "GET_LEAVE_MANAGEMENT_LIST_SUCCESS"; 
export const GET_LEAVE_MANAGEMENT_LIST_ERROR = "GET_LEAVE_MANAGEMENT_LIST_ERROR";

export const ADD_LEAVE_MANAGEMENT_LIST = "ADD_LEAVE_MANAGEMENT_LIST"; 
export const ADD_LEAVE_MANAGEMENT_LIST_SUCCESS = "ADD_LEAVE_MANAGEMENT_LIST_SUCCESS"; 
export const ADD_LEAVE_MANAGEMENT_LIST_ERROR = "ADD_LEAVE_MANAGEMENT_LIST_ERROR";

export const GET_CHANGE_LEAVE_MANAGEMENT_STATUS = "GET_CHANGE_LEAVE_MANAGEMENT_STATUS"; 
export const GET_CHANGE_LEAVE_MANAGEMENT_STATUS_SUCCESS = "GET_CHANGE_LEAVE_MANAGEMENT_STATUS_SUCCESS"; 
export const GET_CHANGE_LEAVE_MANAGEMENT_STATUS_ERROR = "GET_CHANGE_LEAVE_MANAGEMENT_STATUS_ERROR";

export const RESET_LEAVE_MANAGEMENT_LIST = "RESET_LEAVE_MANAGEMENT_LIST"; 
export const RESET_LEAVE_MANAGEMENT_LIST_SUCCESS = "RESET_LEAVE_MANAGEMENT_LIST_SUCCESS"; 
export const RESET_LEAVE_MANAGEMENT_LIST_ERROR = "RESET_LEAVE_MANAGEMENT_LIST_ERROR";

export const GET_LEAVE_LIST = "GET_LEAVE_LIST"; 
export const GET_LEAVE_LIST_SUCCESS = "GET_LEAVE_LIST_SUCCESS"; 
export const GET_LEAVE_LIST_ERROR = "GET_LEAVE_LIST_ERROR";

export const ADD_LEAVE_LIST = "ADD_LEAVE_LIST"; 
export const ADD_LEAVE_LIST_SUCCESS = "ADD_LEAVE_LIST_SUCCESS"; 
export const ADD_LEAVE_LIST_ERROR = "ADD_LEAVE_LIST_ERROR";

export const GET_CHANGE_LEAVE_STATUS = "GET_CHANGE_LEAVE_STATUS"; 
export const GET_CHANGE_LEAVE_STATUS_SUCCESS = "GET_CHANGE_LEAVE_STATUS_SUCCESS"; 
export const GET_CHANGE_LEAVE_STATUS_ERROR = "GET_CHANGE_LEAVE_STATUS_ERROR";