export const GET_HR_DASHBOARD_LIST = "GET_HR_DASHBOARD_LIST"; 
export const GET_HR_DASHBOARD_LIST_SUCCESS = "GET_HR_DASHBOARD_LIST_SUCCESS"; 
export const GET_HR_DASHBOARD_LIST_ERROR = "GET_HR_DASHBOARD_LIST_ERROR";

export const REST_HR_DASHBOARD_LIST = "REST_HR_DASHBOARD_LIST"; 
export const REST_HR_DASHBOARD_LIST_SUCCESS = "REST_HR_DASHBOARD_LIST_SUCCESS"; 
export const REST_HR_DASHBOARD_LIST_ERROR = "REST_HR_DASHBOARD_LIST_ERROR";