export const GET_KANBAN_BOARD = "GET_KANBAN_BOARD"; 
export const GET_KANBAN_BOARD_SUCCESS = "GET_KANBAN_BOARD_SUCCESS"; 
export const GET_KANBAN_BOARD_ERROR = "GET_KANBAN_BOARD_ERROR";

export const ADD_KANBAN_COLUMN = "ADD_KANBAN_COLUMN"; 
export const ADD_KANBAN_COLUMN_SUCCESS = "ADD_KANBAN_COLUMN_SUCCESS"; 
export const ADD_KANBAN_COLUMN_ERROR = "ADD_KANBAN_COLUMN_ERROR";

export const DELETE_KANBAN_COLUMN = "DELETE_KANBAN_COLUMN"; 
export const DELETE_KANBAN_COLUMN_SUCCESS = "DELETE_KANBAN_COLUMN_SUCCESS"; 
export const DELETE_KANBAN_COLUMN_ERROR = "DELETE_KANBAN_COLUMN_ERROR";

export const ADD_KANBAN_TASK = "ADD_KANBAN_TASK"; 
export const ADD_KANBAN_TASK_SUCCESS = "ADD_KANBAN_TASK_SUCCESS"; 
export const ADD_KANBAN_TASK_ERROR = "ADD_KANBAN_TASK_ERROR";

export const UPDATE_KANBAN_TASK = "UPDATE_KANBAN_TASK"; 
export const UPDATE_KANBAN_TASK_SUCCESS = "UPDATE_KANBAN_TASK_SUCCESS"; 
export const UPDATE_KANBAN_TASK_ERROR = "UPDATE_KANBAN_TASK_ERROR";

export const DELETE_KANBAN_TASK = "DELETE_KANBAN_TASK"; 
export const DELETE_KANBAN_TASK_SUCCESS = "DELETE_KANBAN_TASK_SUCCESS"; 
export const DELETE_KANBAN_TASK_ERROR = "DELETE_KANBAN_TASK_ERROR";

export const ADD_SUBTASK = "ADD_SUBTASK"; 
export const ADD_SUBTASK_SUCCESS = "ADD_SUBTASK_SUCCESS"; 
export const ADD_SUBTASK_ERROR = "ADD_SUBTASK_ERROR";

export const DELETE_SUBTASK = "DELETE_SUBTASK"; 
export const DELETE_SUBTASK_SUCCESS = "DELETE_SUBTASK_SUCCESS"; 
export const DELETE_SUBTASK_ERROR = "DELETE_SUBTASK_ERROR";
