export const GET_TESTIMONIAL_LIST = "GET_TESTIMONIAL_LIST"; 
export const GET_TESTIMONIAL_LIST_SUCCESS = "GET_TESTIMONIAL_LIST_SUCCESS"; 
export const GET_TESTIMONIAL_LIST_ERROR = "GET_TESTIMONIAL_LIST_ERROR";

export const ADD_TESTIMONIAL_LIST = "ADD_TESTIMONIAL_LIST"; 
export const ADD_TESTIMONIAL_LIST_SUCCESS = "ADD_TESTIMONIAL_LIST_SUCCESS"; 
export const ADD_TESTIMONIAL_LIST_ERROR = "ADD_TESTIMONIAL_LIST_ERROR";

export const DELETE_TESTIMONIAL_LIST = "DELETE_TESTIMONIAL_LIST"; 
export const DELETE_TESTIMONIAL_LIST_SUCCESS = "DELETE_TESTIMONIAL_LIST_SUCCESS"; 
export const DELETE_TESTIMONIAL_LIST_ERROR = "DELETE_TESTIMONIAL_LIST_ERROR";

export const RESET_TESTIMONIAL_LIST = "RESET_TESTIMONIAL_LIST"; 
export const RESET_TESTIMONIAL_LIST_SUCCESS = "RESET_TESTIMONIAL_LIST_SUCCESS"; 
export const RESET_TESTIMONIAL_LIST_ERROR = "RESET_TESTIMONIAL_LIST_ERROR";