export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"; 
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS"; 
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PRODUCT_VIEW_LIST = "GET_PRODUCT_VIEW_LIST"; 
export const GET_PRODUCT_VIEW_LIST_SUCCESS = "GET_PRODUCT_VIEW_LIST_SUCCESS"; 
export const GET_PRODUCT_VIEW_LIST_ERROR = "GET_PRODUCT_VIEW_LIST_ERROR";

export const RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST"; 
export const RESET_PRODUCT_LIST_SUCCESS = "RESET_PRODUCT_LIST_SUCCESS"; 
export const RESET_PRODUCT_LIST_ERROR = "RESET_PRODUCT_LIST_ERROR";

export const GET_RELATED_PRODUCT_LIST = "GET_RELATED_PRODUCT_LIST"; 
export const GET_RELATED_PRODUCT_LIST_SUCCESS = "GET_RELATED_PRODUCT_LIST_SUCCESS"; 
export const GET_RELATED_PRODUCT_LIST_ERROR = "GET_RELATED_PRODUCT_LIST_ERROR";
