module.exports = {
    CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
    REFERRAL_SUCCESS: 'REFERRAL_SUCCESS',
    ORDER_COMPLETED: 'ORDER_COMPLETED',
    FIRST_ORDER_COMPLETED: 'FIRST_ORDER_COMPLETED',
    PROFILE_COMPLETED: 'PROFILE_COMPLETED',
    BIRTHDAY_REWARD: 'BIRTHDAY_REWARD',
    REVIEW_ADDED: 'REVIEW_ADDED'
};