export const GET_NOTICE_BOARD_LIST = "GET_NOTICE_BOARD_LIST"; 
export const GET_NOTICE_BOARD_LIST_SUCCESS = "GET_NOTICE_BOARD_LIST_SUCCESS"; 
export const GET_NOTICE_BOARD_LIST_ERROR = "GET_NOTICE_BOARD_LIST_ERROR";

export const ADD_NOTICE_BOARD_LIST = "ADD_NOTICE_BOARD_LIST"; 
export const ADD_NOTICE_BOARD_LIST_SUCCESS = "ADD_NOTICE_BOARD_LIST_SUCCESS"; 
export const ADD_NOTICE_BOARD_LIST_ERROR = "ADD_NOTICE_BOARD_LIST_ERROR";

export const DELETE_NOTICE_BOARD_LIST = "DELETE_NOTICE_BOARD_LIST"; 
export const DELETE_NOTICE_BOARD_LIST_SUCCESS = "DELETE_NOTICE_BOARD_LIST_SUCCESS"; 
export const DELETE_NOTICE_BOARD_LIST_ERROR = "DELETE_NOTICE_BOARD_LIST_ERROR";

export const RESET_NOTICE_BOARD_LIST = "RESET_NOTICE_BOARD_LIST"; 
export const RESET_NOTICE_BOARD_LIST_SUCCESS = "RESET_NOTICE_BOARD_LIST_SUCCESS"; 
export const RESET_NOTICE_BOARD_LIST_ERROR = "RESET_NOTICE_BOARD_LIST_ERROR";