export const GET_REFERRAL_RULES_LIST = "GET_REFERRAL_RULES_LIST"; 
export const GET_REFERRAL_RULES_LIST_SUCCESS = "GET_REFERRAL_RULES_LIST_SUCCESS"; 
export const GET_REFERRAL_RULES_LIST_ERROR = "GET_REFERRAL_RULES_LIST_ERROR";

export const ADD_REFERRAL_RULES_LIST = "ADD_REFERRAL_RULES_LIST"; 
export const ADD_REFERRAL_RULES_LIST_SUCCESS = "ADD_REFERRAL_RULES_LIST_SUCCESS"; 
export const ADD_REFERRAL_RULES_LIST_ERROR = "ADD_REFERRAL_RULES_LIST_ERROR";

export const CHANGE_STATUS_REFERRAL_RULES_LIST = "CHANGE_STATUS_REFERRAL_RULES_LIST"; 
export const CHANGE_STATUS_REFERRAL_RULES_LIST_SUCCESS = "CHANGE_STATUS_REFERRAL_RULES_LIST_SUCCESS"; 
export const CHANGE_STATUS_REFERRAL_RULES_LIST_ERROR = "CHANGE_STATUS_REFERRAL_RULES_LIST_ERROR";

export const DELETE_REFERRAL_RULES_LIST = "DELETE_REFERRAL_RULES_LIST"; 
export const DELETE_REFERRAL_RULES_LIST_SUCCESS = "DELETE_REFERRAL_RULES_LIST_SUCCESS"; 
export const DELETE_REFERRAL_RULES_LIST_ERROR = "DELETE_REFERRAL_RULES_LIST_ERROR";

export const REST_REFERRAL_RULES_LIST = "REST_REFERRAL_RULES_LIST"; 
export const REST_REFERRAL_RULES_LIST_SUCCESS = "REST_REFERRAL_RULES_LIST_SUCCESS"; 
export const REST_REFERRAL_RULES_LIST_ERROR = "REST_REFERRAL_RULES_LIST_ERROR";