export const GET_TESTIMONIAL_LIST = "GET_TESTIMONIAL_LIST"; 
export const GET_TESTIMONIAL_LIST_SUCCESS = "GET_TESTIMONIAL_LIST_SUCCESS"; 
export const GET_TESTIMONIAL_LIST_ERROR = "GET_TESTIMONIAL_LIST_ERROR";